<REQUEST_FPXXXZ_NEW class="REQUEST_FPXXXZ_NEW">
	<FPQQLSH>${FPQQLSH?if_exists}</FPQQLSH>
	<DSPTBM>${DSPTBM?if_exists}</DSPTBM>
	<NSRSBH>${NSRSBH?if_exists}</NSRSBH>
	<DDH>${DDH?if_exists}</DDH>
	<PDF_XZFS>${PDF_XZFS?if_exists}</PDF_XZFS>
</REQUEST_FPXXXZ_NEW>