
package com.gionee.dc.web.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-03-11T17:33:18.778+08:00
 * Generated source version: 2.6.0
 */

@WebFault(name = "Exception", targetNamespace = "http://service.web.dc.gionee.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.gionee.dc.web.service.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.gionee.dc.web.service.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.gionee.dc.web.service.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.gionee.dc.web.service.Exception getFaultInfo() {
        return this.exception;
    }
}
