package com.gionee.dc.web.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-03-11T17:33:18.805+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://service.web.dc.gionee.com/", name = "SaleInvoice")
@XmlSeeAlso({ObjectFactory.class})
public interface SaleInvoice {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addSaleInvoice", targetNamespace = "http://service.web.dc.gionee.com/", className = "com.gionee.dc.web.service.AddSaleInvoice")
    @WebMethod
    @ResponseWrapper(localName = "addSaleInvoiceResponse", targetNamespace = "http://service.web.dc.gionee.com/", className = "com.gionee.dc.web.service.AddSaleInvoiceResponse")
    public java.lang.String addSaleInvoice(
        @WebParam(name = "arg0", targetNamespace = "")
        com.gionee.dc.web.service.AuthInfo arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<com.gionee.dc.web.service.ImeidtlSale> arg1
    ) throws Exception_Exception;
}
