package com.gionee.dc.web.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.gionee.dc.web.service.SaleInvoice;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-03-11T17:33:18.822+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "SaleInvoiceImplService", 
                  wsdlLocation = "http://www.datatransetl.com:8082/dc/services/saleInvoice?wsdl",
                  targetNamespace = "http://impl.service.web.dc.gionee.com/") 
public class SaleInvoiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.web.dc.gionee.com/", "SaleInvoiceImplService");
    public final static QName SaleInvoiceImplPort = new QName("http://impl.service.web.dc.gionee.com/", "SaleInvoiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://www.datatransetl.com:8082/dc/services/saleInvoice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SaleInvoiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.datatransetl.com:8082/dc/services/saleInvoice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SaleInvoiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SaleInvoiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SaleInvoiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SaleInvoice
     */
    @WebEndpoint(name = "SaleInvoiceImplPort")
    public SaleInvoice getSaleInvoiceImplPort() {
        return super.getPort(SaleInvoiceImplPort, SaleInvoice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SaleInvoice
     */
    @WebEndpoint(name = "SaleInvoiceImplPort")
    public SaleInvoice getSaleInvoiceImplPort(WebServiceFeature... features) {
        return super.getPort(SaleInvoiceImplPort, SaleInvoice.class, features);
    }

}
