package com.sf.integration.warehouse.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-08-26T11:17:07.296+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://service.warehouse.integration.sf.com/", name = "IOutsideToLscmService")
@XmlSeeAlso({ObjectFactory.class})
public interface IOutsideToLscmService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "yxToLscmService", targetNamespace = "http://service.warehouse.integration.sf.com/", className = "com.sf.integration.warehouse.service.YxToLscmService")
    @WebMethod
    @ResponseWrapper(localName = "yxToLscmServiceResponse", targetNamespace = "http://service.warehouse.integration.sf.com/", className = "com.sf.integration.warehouse.service.YxToLscmServiceResponse")
    public java.lang.String yxToLscmService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "jyToLscmService", targetNamespace = "http://service.warehouse.integration.sf.com/", className = "com.sf.integration.warehouse.service.JyToLscmService")
    @WebMethod
    @ResponseWrapper(localName = "jyToLscmServiceResponse", targetNamespace = "http://service.warehouse.integration.sf.com/", className = "com.sf.integration.warehouse.service.JyToLscmServiceResponse")
    public java.lang.String jyToLscmService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "outsideToLscmService", targetNamespace = "http://service.warehouse.integration.sf.com/", className = "com.sf.integration.warehouse.service.OutsideToLscmService")
    @WebMethod
    @ResponseWrapper(localName = "outsideToLscmServiceResponse", targetNamespace = "http://service.warehouse.integration.sf.com/", className = "com.sf.integration.warehouse.service.OutsideToLscmServiceResponse")
    public java.lang.String outsideToLscmService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
