package com.gionee.wms.entity;

import java.util.Date;

public class SalesOrderLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WMS_SALES_ORDER_LOG.ID
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WMS_SALES_ORDER_LOG.ORDER_ID
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WMS_SALES_ORDER_LOG.ORDER_STATUS
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    private int orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WMS_SALES_ORDER_LOG.OP_USER
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    private String opUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WMS_SALES_ORDER_LOG.OP_TIME
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WMS_SALES_ORDER_LOG.REMARK
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WMS_SALES_ORDER_LOG.ID
     *
     * @return the value of WMS_SALES_ORDER_LOG.ID
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WMS_SALES_ORDER_LOG.ID
     *
     * @param id the value for WMS_SALES_ORDER_LOG.ID
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WMS_SALES_ORDER_LOG.ORDER_ID
     *
     * @return the value of WMS_SALES_ORDER_LOG.ORDER_ID
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WMS_SALES_ORDER_LOG.ORDER_ID
     *
     * @param orderId the value for WMS_SALES_ORDER_LOG.ORDER_ID
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WMS_SALES_ORDER_LOG.ORDER_STATUS
     *
     * @return the value of WMS_SALES_ORDER_LOG.ORDER_STATUS
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    public int getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WMS_SALES_ORDER_LOG.ORDER_STATUS
     *
     * @param orderStatus the value for WMS_SALES_ORDER_LOG.ORDER_STATUS
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    public void setOrderStatus(int orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WMS_SALES_ORDER_LOG.OP_USER
     *
     * @return the value of WMS_SALES_ORDER_LOG.OP_USER
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    public String getOpUser() {
        return opUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WMS_SALES_ORDER_LOG.OP_USER
     *
     * @param opUser the value for WMS_SALES_ORDER_LOG.OP_USER
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    public void setOpUser(String opUser) {
        this.opUser = opUser == null ? null : opUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WMS_SALES_ORDER_LOG.OP_TIME
     *
     * @return the value of WMS_SALES_ORDER_LOG.OP_TIME
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WMS_SALES_ORDER_LOG.OP_TIME
     *
     * @param opTime the value for WMS_SALES_ORDER_LOG.OP_TIME
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WMS_SALES_ORDER_LOG.REMARK
     *
     * @return the value of WMS_SALES_ORDER_LOG.REMARK
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WMS_SALES_ORDER_LOG.REMARK
     *
     * @param remark the value for WMS_SALES_ORDER_LOG.REMARK
     *
     * @mbggenerated Wed Feb 12 16:04:23 GMT+08:00 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}