package com.routdata.zzfw.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-03-31T13:56:11.954+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://service.webservice.zzfw.routdata.com/", name = "IMailQueryService")
@XmlSeeAlso({ObjectFactory.class})
public interface IMailQueryService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryMail", targetNamespace = "http://service.webservice.zzfw.routdata.com/", className = "com.routdata.zzfw.webservice.service.QueryMail")
    @WebMethod
    @ResponseWrapper(localName = "queryMailResponse", targetNamespace = "http://service.webservice.zzfw.routdata.com/", className = "com.routdata.zzfw.webservice.service.QueryMailResponse")
    public java.lang.String queryMail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws SQLException_Exception, BusinessException_Exception, SysException_Exception;
}
