
package com.routdata.zzfw.webservice.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-03-31T13:56:11.828+08:00
 * Generated source version: 2.6.0
 */

@WebFault(name = "SQLException", targetNamespace = "http://service.webservice.zzfw.routdata.com/")
public class SQLException_Exception extends Exception {
    
    private com.routdata.zzfw.webservice.service.SQLException sqlException;

    public SQLException_Exception() {
        super();
    }
    
    public SQLException_Exception(String message) {
        super(message);
    }
    
    public SQLException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SQLException_Exception(String message, com.routdata.zzfw.webservice.service.SQLException sqlException) {
        super(message);
        this.sqlException = sqlException;
    }

    public SQLException_Exception(String message, com.routdata.zzfw.webservice.service.SQLException sqlException, Throwable cause) {
        super(message, cause);
        this.sqlException = sqlException;
    }

    public com.routdata.zzfw.webservice.service.SQLException getFaultInfo() {
        return this.sqlException;
    }
}
