<REQUEST_FPKJXX class="REQUEST_FPKJXX ">
	<FPKJXX_FPTXX class="FPKJXX_FPTXX">
		<FPQQLSH>${version?if_exists}</FPQQLSH>
		<DSPTBM>${version?if_exists}</DSPTBM>
		<NSRSBH>${version?if_exists}</NSRSBH>
		<NSRMC>${version?if_exists}</NSRMC>
		<NSRDZDAH>${version?if_exists}</NSRDZDAH>
		<SWJG_DM>${version?if_exists}</SWJG_DM>
		<DKBZ>${version?if_exists}</DKBZ>
		<PYDM>${version?if_exists}</PYDM>
		<KPXM>${version?if_exists}</KPXM>
		<BMB_BBH>${version?if_exists}</BMB_BBH>
		<XHF_NSRSBH>${version?if_exists}</XHF_NSRSBH>
		<XHFMC>${version?if_exists}</XHFMC>
		<XHF_DZ>${version?if_exists}</XHF_DZ>
		<XHF_DH>${version?if_exists}</XHF_DH>
		<XHF_YHZH>${version?if_exists}</XHF_YHZH>
		<GHFMC>${version?if_exists}</GHFMC>
		<GHF_NSRSBH>${version?if_exists}</GHF_NSRSBH>
		<GHF_SF>${version?if_exists}</GHF_SF>
		<GHF_DZ>${version?if_exists}</GHF_DZ>
		<GHF_GDDH>${version?if_exists}</GHF_GDDH>
		<GHF_SJ>${version?if_exists}</GHF_SJ>
		<GHF_EMAIL>${version?if_exists}</GHF_EMAIL>
		<GHFQYLX>${version?if_exists}</GHFQYLX>
		<GHF_YHZH>${version?if_exists}</GHF_YHZH>
		<HY_DM>${version?if_exists}</HY_DM>
		<HY_MC>${version?if_exists}</HY_MC>
		<KPY>${version?if_exists}</KPY>
		<SKY>${version?if_exists}</SKY>
		<FHR>${version?if_exists}</FHR>
		<KPRQ>${version?if_exists}</KPRQ>
		<KPLX>${version?if_exists}</KPLX>
		<YFP_DM>${version?if_exists}</YFP_DM>
		<YFP_HM>${version?if_exists}</YFP_HM>
		<CZDM>${version?if_exists}</CZDM>
		<QD_BZ>${version?if_exists}</QD_BZ>
		<QDXMMC>${version?if_exists}</QDXMMC>
		<CHYY>${version?if_exists}</CHYY>
		<TSCHBZ>${version?if_exists}</TSCHBZ>
		<KPHJJE>${version?if_exists}</KPHJJE>
		<HJBHSJE>${version?if_exists}</HJBHSJE>
		<HJSE>${version?if_exists}</HJSE>
		<BZ>${version?if_exists}</BZ>
		<BYZD1>${version?if_exists}</BYZD1>
		<BYZD2>${version?if_exists}</BYZD2>
		<BYZD3>${version?if_exists}</BYZD3>
		<BYZD4>${version?if_exists}</BYZD4>
		<BYZD5>${version?if_exists}</BYZD5>
	</FPKJXX_FPTXX>
	<FPKJXX_XMXXS class="FPKJXX_XMXX;" size="1">
		<FPKJXX_XMXX>
			<XMMC>${version?if_exists}</XMMC>
			<XMDW>${version?if_exists}</XMDW>
			<GGXH>${version?if_exists}</GGXH>
			<XMSL>${version?if_exists}</XMSL>
			<HSBZ>${version?if_exists}</HSBZ>
			<XMDJ>${version?if_exists}</XMDJ>
			<FPHXZ>${version?if_exists}</FPHXZ>
			<SPBM>${version?if_exists}</SPBM>
			<ZXBM>${version?if_exists}</ZXBM>
			<YHZCBS>${version?if_exists}</YHZCBS>
			<LSLBS>
				<LSLBS/>
				<ZZSTSGL>${version?if_exists}</ZZSTSGL>
				<XMJE>${version?if_exists}</XMJE>
				<SL>${version?if_exists}</SL>
				<SE>${version?if_exists}</SE>
				<BYZD1>${version?if_exists}</BYZD1>
				<BYZD2>${version?if_exists}</BYZD2>
				<BYZD3>${version?if_exists}</BYZD3>
				<BYZD4>${version?if_exists}</BYZD4>
				<BYZD5>${version?if_exists}</BYZD5>
		</FPKJXX_XMXX>
	</FPKJXX_XMXXS>
	<FPKJXX_DDXX class="FPKJXX_DDXX">
		<DDH>${version?if_exists}</DDH>
		<THDH>${version?if_exists}</THDH>
		<DDDATE>${version?if_exists}</DDDATE>
	</FPKJXX_DDXX>
	<FPKJXX_DDMXXXS class="FPKJXX_DDMXXX;" size="1">
		<FPKJXX_DDMXXX>
			<DDMC>${version?if_exists}</DDMC>
			<DW>${version?if_exists}</DW>
			<GGXH>${version?if_exists}</GGXH>
			<SL>${version?if_exists}</SL>
			<DJ>${version?if_exists}</DJ>
			<JE>${version?if_exists}</JE>
			<BYZD1>${version?if_exists}</BYZD1>
			<BYZD2>${version?if_exists}</BYZD2>
			<BYZD3>${version?if_exists}</BYZD3>
			<BYZD4>${version?if_exists}</BYZD4>
			<BYZD5>${version?if_exists}</BYZD5>
		</FPKJXX_DDMXXX>
	</FPKJXX_DDMXXXS>
	<FPKJXX_ZFXX class=" FPKJXX_ZFXX">
		<ZFFS>${version?if_exists}</ZFFS>
		<ZFLSH>${version?if_exists}</ZFLSH>
		<ZFPT>${version?if_exists}</ZFPT>
	</FPKJXX_ZFXX>
	<FPKJXX_WLXX class=" FPKJXX_WLXX">
		<CYGS>${version?if_exists}</CYGS>
		<SHSJ>${version?if_exists}</SHSJ>
		<WLDH>${version?if_exists}</WLDH>
		<SHDZ>${version?if_exists}</SHDZ>
	</FPKJXX_WLXX>
</REQUEST_FPKJXX>