package com.sf.integration.expressservice.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2017-08-14T10:10:29.438+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "CommonExpressServiceService", 
                  wsdlLocation = "http://bsp-ois.sit.sf-express.com:9080/bsp-ois/ws/sfexpressService?wsdl",
                  targetNamespace = "http://service.expressservice.integration.sf.com/") 
public class CommonExpressServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.expressservice.integration.sf.com/", "CommonExpressServiceService");
    public final static QName CommonExpressServicePort = new QName("http://service.expressservice.integration.sf.com/", "CommonExpressServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://bsp-ois.sit.sf-express.com:9080/bsp-ois/ws/sfexpressService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CommonExpressServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://bsp-ois.sit.sf-express.com:9080/bsp-ois/ws/sfexpressService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CommonExpressServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CommonExpressServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonExpressServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CommonExpressServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CommonExpressServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CommonExpressServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IExpressService
     */
    @WebEndpoint(name = "CommonExpressServicePort")
    public IExpressService getCommonExpressServicePort() {
        return super.getPort(CommonExpressServicePort, IExpressService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IExpressService
     */
    @WebEndpoint(name = "CommonExpressServicePort")
    public IExpressService getCommonExpressServicePort(WebServiceFeature... features) {
        return super.getPort(CommonExpressServicePort, IExpressService.class, features);
    }

}
