
package com.sf.integration.expressservice.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.15
 * 2017-03-01T15:46:19.177+08:00
 * Generated source version: 2.6.15
 * 
 */
public final class IExpressService_CommonExpressServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.expressservice.integration.sf.com/", "CommonExpressServiceService");

    private IExpressService_CommonExpressServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CommonExpressServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CommonExpressServiceService ss = new CommonExpressServiceService(wsdlURL, SERVICE_NAME);
        IExpressService port = ss.getCommonExpressServicePort();  
        
        {
        System.out.println("Invoking sfexpressService...");
        java.lang.String _sfexpressService_arg0 = "";
        java.lang.String _sfexpressService_arg1 = "";
        java.lang.String _sfexpressService__return = port.sfexpressService(_sfexpressService_arg0, _sfexpressService_arg1);
        System.out.println("sfexpressService.result=" + _sfexpressService__return);


        }

        System.exit(0);
    }

}
