package com.sf.integration.expressservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2018-01-17T18:03:32.881+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://service.expressservice.integration.sf.com/", name = "IExpressService")
@XmlSeeAlso({ObjectFactory.class})
public interface IExpressService {

    @WebMethod
    @RequestWrapper(localName = "sfexpressService", targetNamespace = "http://service.expressservice.integration.sf.com/", className = "com.sf.integration.expressservice.service.SfexpressService")
    @ResponseWrapper(localName = "sfexpressServiceResponse", targetNamespace = "http://service.expressservice.integration.sf.com/", className = "com.sf.integration.expressservice.service.SfexpressServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sfexpressService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
